canonical/desktop-engineering

- gh-actions/common/build-debian/action.yml
This action builds a debian package at a specified path and uploads the artifacts generated. It is a wrapper around jtdor/build-deb-action, which itself uses dpkg.
It needs:
- the source dir: where the debian/ folder is located
- docker-image: where the package will be built, and as such the release to target
- token: This one is optional. If provided, it is used to grant git  access to private repos, which is necessary to fetch Go private packages
This action has been tested and is in use in a private repository of the Canonical organization.
UDENG-878
> Implement build-debian action

- .github/CODEOWNERS
The codeowner file syntax is actually overriding previous rules and is not cumulative. We can assign owners for subparts of the trees, but without rule, this is a global override.
Then, ensure that both owners are assigned for review on this repository.
> fix(github): Ensure correct group of people is set for reviews

- project-repo/review-process.md
Just noticed a repetition fo the adverb "currently" in the sentence about Launchpad and a reference to serotonin instead of dopamine (it's a quite common confusion around those two neurotransmitters 😉 [check here](https://my.clevelandclinic.org/health/articles/22572-serotonin#:~:text=Dopamine%20is%20associated%20with%20rewards%20and%20motivation), [here](https://www.medicalnewstoday.com/articles/326090#dopamine:~:text=Dopamine%20plays%20an%20integral%20role%20in%20the%20reward%20system%2C%20a%20group%20of%20brain%20processes%20that%20control%20motivation%2C%20desire%2C%20and%20cravings) and [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6760372/#:~:text=Dopamine%20release%20may%20be%20associated%20with%20the%20pleasurable%20or%20rewarding%20effects%20of%20AODs%20and%20with%20the%20mot …
> maint(processes): typos and semantic

- gh-actions/common/has-diff/action.yml
- gh-actions/go/code-sanity/action.yaml
- gh-actions/go/generate/action.yaml
This is useful (needed really) if you need to run actions on a sub-directory of a monorepo.
> feat(gh-actions): allow action caller to specify a working directory

- gh-actions/go/code-sanity/action.yaml
> fix(gh-actions): adapt workaround for golangci-lint on mono-repo

- gh-actions/common/has-diff/action.yml
- gh-actions/common/print-summary/action.yml
- gh-actions/go/code-sanity/action.yaml
- gh-actions/go/generate/action.yaml
Strictly necessary:
- (85a1bbc) `sudo` is not available on Windows.
- (e3c87d8) `rev` is not available on Windows. I switched to using jq to parse go mod files.
- (5996fb2) Treat Linux-specific workarounds with more finesse.
- (d88da61, 9068ca3) Windows path arguments are passed `\with\back\slashes` which are read by bash as `withbackslashes`, making all usage of `cd` fail.
A couple QoL things:
- (2c5235b) Use single quotes around '${{ github.variable }}' to avoid weird interactions with special characters (were possible). Github pretty much acts like the C pre-processor here.
- (e5d5938) Added a ::group:: were I saw `apt` spam.
---
UDENG-1399
> fix(gh-actions): Fix Windows issues in cross-platform Github actions

- .github/workflows/pr-title-check.yaml
- gh-actions/common/validate-pr-title/action.yaml
This pull request implements a Github action to validate pull request titles. It ensures that it follows schema `tag(optional-component): Some description`, and then ensures that the tag is in the pre-approved list.
As far as I understand, the workflow won't be triggered during this PR, as in needs to be in the main branch. I did some testing in another repo though, You can see and example PR and some workflow runs here: https://github.com/EduardGomezEscandell/test/pull/1
---
UDENG-1510
> feat(gh-actions): implement validate-pr-title action

- project-repo/review-process.md
Add a guideline enforcing that team members should sign their commits.
This is not mandatory for external contributors.
> feat(project-repo): Make note about signing commits

- gh-actions/go/code-sanity/action.yaml
Use go version to detect which go toolchain the project is depending on, now that go version does this analyze since go1.21.0.
> feat: use go version

- gh-actions/go/generate/action.yaml
Parse the tools using jq so that we can easily get the tool path and version and install the one explicitly requested
> generate: Use go mod edit to install properly versioned tools

- .github/dependabot.yml
Unfortunately, we need to track each actions file manually as dependabot doesn’t look recursively in directory.
UDENG-2526
> feat(ci): track GH action updates

- gh-actions/go/code-sanity/action.yaml
This update allows to remove an hack that was previously necessary. Also, we need v6 now for GH to accepts the annotations format.
UDENG-4223
> maint: update golangci-lint action

- .github/workflows/test-build-deb.yaml
- gh-actions/common/build-debian/action.yml
- gh-actions/go/generate/action.yaml
As underlined in https://github.com/ubuntu/authd/pull/130#issuecomment-1963005213 using `jtdor/build-deb-action` for building debian packages has some problems that are yet not clear, and it also does not seem to properly support building non-native packages.
As per this, given that the code needed for handling the build inside a simpler docker container is quite small, I've moved the build to manual handling which allows us some more control over the steps at the cost of being a bit more verbose.
As bonus:
- We now only build as user (not the sources, since there's no much point)
- All the network traffic is totally blocked for the builder user (not just HTTPS)
- `DEB_BUILD_OPTIONS` can be customized for special builds (e.g. `nocheck`)
- Version uses actual distro version
I've added some …
> feat(build-debian): Use docker to manually run build and prepare steps and add tests

- bin/jira
the arguments parsing will be used as a base to add other options
> feat: add an option to not assign the new cards

- gh-actions/go/gotestfmt/action.yaml
- gh-actions/go/gotestfmt/gotestfmt
The output of `go test` is notoriously hard to read, especially when a lot of tests are executed and a lot of output is produced. [gotestfmt](https://github.com/GoTestTools/gotestfmt) can hide the output of successful tests and put the output of failed tests in an expandable group.
This PR adds a custom GitHub Action which installs gotestfmt and a wrapper script which improves the output and copies it to log files, which can then be uploaded as test artifacts.
You can see an example of the produced output when a test fails in [this job](https://github.com/ubuntu/authd-oidc-brokers/actions/runs/11819017382/job/32928619473?pr=220). A link to the artifacts of that job can be found in the ["Upload test artifacts" step](https://github.com/ubuntu/authd-oidc-brokers/actions/runs/11819017382/job/3 …
> gh-actions: Add action to install gotestfmt and our wrapper script

- bin/jira-tools.py
When I made story points for tickets optional I failed to correctly nest the key under `fields` when setting the custom field outside of the in initial payload creation.
> fix: correcting key for setting story points

- bin/jira
To fix
```
% ./jira new task Integration Test
jq: error (at <stdin>:0): Cannot iterate over null (null)
Project: UDENG
Summary: Test
Type: task
Component: Integration
Description:
Enter issue body here...
:: Create a new issue with these details? [y/n]
y
:: Creating issue...
{"errorMessages":["Issue does not exist or you do not have permission to see it."],"errors":{}}:: Issue created and added to active pulse: https://warthogs.atlassian.net/browse/null
```
> fix: Uppercase first letter of issue type.

- bin/jira
`jq` returns "null" when the "key" field is not present in the response.
Also, print the response (which contains the error message returned by the server) on error.
> fix: Fix error handling

- .github/workflows/test-build-deb.yaml
- gh-actions/common/build-debian/action.yml
When building some packages we may need to prepare the build environment before preparing the source package, for example in some cases we may need to enable git access (to compute the package version or similar) or we may need to install tools that are used during debian source building that are not provided in the archive (such as rust crates, hello cargo-vendor-filterer!!).
So instead of polluting this generic action with package-specific requirements, let's just make it support running a script that can do more advanced configurations in the docker instance that is used only during the source-preparation phase.
Not covering the migration yet (since I'd like to provide some more tools for it), but I think that we should drop the specific-git code from this action too, and move it where …
> feat(gh-actions/build-debian): Support running a workflow script at build-source phase

- gh-actions/go/gotestfmt/action.yaml
Use our fork until https://github.com/GoTestTools/gotestfmt/pull/62 has been merged by upstream.
UDENG-5451
> fix(gotestfmt): Fix incorrect gotestfmt output

- gh-actions/go/code-sanity/action.yaml
- gh-actions/go/gotestfmt/action.yaml
Updates to add macOS compatibility for go code-sanity and gotestfmt
- Use brew to install jq in code-sanity
- Remove and replace unsupported flags in the install command for gotestfmt
- Use mkdir instead of -D
- Remove -t
- Use -m instead of --mode
Minor spelling fix
---
UDENG-5777
> feat(gh-actions): Add macOS compatibility for go code-sanity and gotestfmt

- .github/workflows/test-build-deb.yaml
- gh-actions/common/build-debian/action.yml
- gh-actions/common/run-autopkgtest/action.yml
It allows to run autopkgtests in an LXD container for a both a source
files and/or provided built debs
Add test cases
UDENG-2343
> feat(gh-actions): Add run-autopkgtest action

- .github/workflows/test-build-deb.yaml
- gh-actions/common/build-debian/action.yml
- gh-actions/common/build-debian/prepare-container.sh
Simplify the action and move the common docker steps in a script that is shared by all the steps.
> cleanup(gh-actions/build-debian): Unify steps common tasks and make apt faster

- gh-actions/common/run-autopkgtest/action.yml
It contains the fix to speedup the image creation, and we can trust that main will be well managed.
If not we can always go back to a version we know it works.
> maint(gh-actions/run-autopkgtests): Use main branch for setup-lxd

- project-repo/templates/common/.github/workflows/cla-check.yaml
Following a recent notification in discourse.canonical.com, the github workflow must be updated to V2 before the end of March.
https://discourse.canonical.com/t/new-contributor-license-agreement-cla-service/5247
This PR does that.
> maint(gh-actions): Update CLA check to v2

- gh-actions/rust/code-sanity/action.yaml
The step succeeded even if the Rust code is not formatted correctly. That's because running `cargo fmt` formats the code and exits with 0. We want `cargo fmt --check` instead, which doesn't actually format the code but checks if it needs formatting, and exits with 1.
> fix(rust/code-sanity): Fix "rustfmt-check" step

- gh-actions/common/run-autopkgtest/action.yml
This seems to be now a required component by autopkgtest-build-lxd
See: https://github.com/canonical/setup-lxd/issues/31
> fix(gh-actions/run-autopkgtests): Install dnsmasq-base

- gh-actions/common/gh-perms/action.yaml
Shell is required in composite actions.
Also the token in an input.
Otherwise
🙈
> fix: GH perms action run steps missing shell

- gh-actions/go/gotestfmt/gotestfmt
Currently, `gotestfmt` does not know how to handle outputs from `go test` where the `Action` field is "build-outputs". If it receives a line of this type, then it will panic and print out a byte-encoded string representation of that input's `Output` field.
From what I've seen, this kind of output usually occurs due to a warning output from an underlying toolchain like GCC when using CGo. They can be suppressed with `CGO_LDFLAGS="-w"` but this resolution isn't always intuitive due to how the issue manifests itself. Additionally, these warnings may be genuinely useful.
This PR diverts lines where the `Action` field is "build-outputs", wrapping the line with some additional context and sending it to stderr instead of allowing it to be passed forwards to `gotestfmt` which would in turn panic. …
> feat(gotestfmt): Divert "build-output" actions

- gh-actions/rust/code-sanity/action.yaml
The actions-rs GitHub Actions were archived in Oct 2023.
We don't need a GitHub Action anymore to install Rust, because we can just use rustup for that, which is pre-installed on the GitHub runner images.
UDENG-7853
> maint: Replace unmaintained actions-rs GitHub Actions

- gh-actions/go/code-sanity/action.yaml
Turns out `jq` is included in the GitHub runner images already, so this step isn't needed and, in fact, results in the warning annotation: `jq 1.8.1 is already installed and up-to-date. To reinstall 1.8.1, run: brew reinstall jq`
I wanted to keep the default as Linux, so instead I just made the macOS branch do nothing.
See this run for an example of these changes in use; note the lack of warning annotations now: https://github.com/ubuntu/ubuntu-insights/actions/runs/17302233750?pr=231
> fix(go/code-sanity): Remove macOS jq installation step

- gh-actions/common/dpkg-exclude-locales-and-manpages/action.yml
- gh-actions/common/dpkg-install-speedup/action.yml
This GitHub Action configures dpkg to exclude locales and manpages from installed packages, speeding up package installation. We should use it in all jobs which use APT to install packages, because it can significantly speed up the installation time. Avoiding the man-db triggers alone can reduce the installation time by up to two minutes.
UDENG-7865
> feat: Add GitHub Action common/dpkg-exclude-locales-and-manpages

- gh-actions/go/code-sanity/action.yaml
Unless `GOTOOLCHAIN` is specified, the Go version used by `go install` to build the binary is determined by:
1. The `toolchain` directive in the `go.mod` of the module being installed
2. If there is no `toolchain` directive in the `go.mod` of the module being installed, the system's Go is used (the one in PATH).
We specify the Go version that should be used for tools like govulncheck in `tools/go.mod`. So we need to point `GOTOOLCHAIN` to that to actually use that Go version when building govulncheck.
This avoids errors like:
Error: /home/runner/go/pkg/mod/golang.org/x/sys@v0.35.0/unix/vgetrandom_linux.go:7:9: file requires newer Go version go1.24 (application built with go1.23)
which occur when govulncheck is built with an older Go version than the required version of the module that it …
> fix: Install govulncheck with the correct Go toolchain version
